env:
  GLOBAL_TIMEOUT: 60

steps:
  - input: "Parametersss"
    fields:
      - text: "APP_VERSION"
        hint: "Provide App Version if different from defaulttsss"
        required: false
        key: app-version
  - label: "Unit Testsss"
    key: "unit_tests"
    command: "echo test global timeoutsddssssss"

  - trigger: "app-deploy"
    build:
      message: this commit should cAA$$A$ ause issues

      
                 

